apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.name }}-kv-secrets
  namespace: organistation-ns
spec:
  provider: azure
  secretObjects:                              # This syncs the KV secret into a K8s Secret
    - secretName: {{ .Values.name }}-secret
      type: Opaque
      data:
        {{- range .Values.secrets }}
        - objectName: {{ .name }}
          key: {{ .key }}
        {{- end }}
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Best practice: use the VM's managed identity
    userAssignedIdentityID: {{ .Values.global.userAssignedIdentityID | default "" }}
    keyvaultName: {{ .Values.global.keyvaultName }}
    cloudName: ""                         # [Optional] Default is AzurePublicCloud
    objects: |
      array:
        {{- range .Values.secrets }}
        - |
          objectName: {{ .name }}
          objectType: secret              # [Required] Type of object in Key Vault
        {{- end }}
    tenantId: {{ .Values.global.azureTenantId }}
