apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.name }}-kv-secrets
  namespace: organistation-ns
spec:
  provider: azure
  {{- if .Values.secrets }}
  secretObjects:
    - secretName: {{ .Values.name }}-secret
      type: Opaque
      data:
        {{- range .Values.secrets }}
        - objectName: {{ .name }}
          key: {{ .key }}
        {{- end }}
  {{- end }}
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.global.userAssignedIdentityID }}
    keyvaultName: {{ .Values.global.keyvaultName }}
    objects: |
      array:
        {{- range .Values.secrets }}
        - |
          objectName: {{ .name }}
          objectType: secret
        {{- end }}
    tenantId: {{ .Values.global.azureTenantId }}
